"""add clash link

Revision ID: 52185304f6a6
Revises: 2b231de97dc3
Create Date: 2025-02-09 20:45:18.423773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52185304f6a6'
down_revision = '2b231de97dc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clash_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64, collation='NOCASE'), nullable=False),
    sa.Column('tag', sa.String(length=64, collation='NOCASE'), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('user_agent', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tag')
    )
    op.create_index(op.f('ix_clash_profiles_id'), 'clash_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_clash_profiles_name'), 'clash_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_clash_profiles_tag'), 'clash_profiles', ['tag'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_clash_profiles_tag'), table_name='clash_profiles')
    op.drop_index(op.f('ix_clash_profiles_name'), table_name='clash_profiles')
    op.drop_index(op.f('ix_clash_profiles_id'), table_name='clash_profiles')
    op.drop_table('clash_profiles')
    # ### end Alembic commands ###
